### ISSUE TITLE
Add new City/ Add new Country functionality

### ISSUE THREAD

**Issue by M3f1st0** [M3f1st0/MiuZiKs_Official_V2#2]
The New User Creation procedure should include the option to add a new Country/City.
Class: NewUserCreationController.java

**Comment by cwsexton** [comment]
Have created option for user to Add City upon account creation. ComboBox becomes editable if user chooses "Add City" and a method in NewUserController takes the user defined city, double checks to make sure it's not already registered, then saves it to database before enterUser process is begun.

Also fixed saveCity method in DBHandler, which was previously attempting to put CountryName string into city database as CountryID. Also, the "resource" url for Admin City controller was messed up so it loaded Record Companies upon save, rather than reloading cities - this was also fixed.

Have not added an "add Country" feature so far because I am not sure a user should be able to add a new country. We have a list of all recognized world countries and I think it's an admin responsibility to keep that updated - users specifying their own countries, based on personal politics and such, is maybe not desirable. But if you disagree I can add it.
